name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 5.0.0
homepage: https://github.com/justkawal/excel
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ^3.7.2

dependencies:
  web: ^1.1.1
  archive: ^4.0.7
  xml: ^6.6.1
  collection: ^1.19.1
  equatable: ^2.0.8

dev_dependencies:
  test: ^1.29.0
  lints: ^6.1.0
